---
title: "bayesian_stats_ch3_poisson"
author: "inoue jin"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(tidyverse, ggthemes, ggpubr, RColorBrewer)

```

総合的社会調査（GSS）は、40歳の女性155人の学歴と子供の数に関するデータを収集。

学士号を持つかどうか($Y=1$)で、女性の子供の数を比較する。

$Y_{i,1}$ を学士号を持たない$n_{1}$人の女性の子供の数とし、$Y_{i,2}$を学士号を持つ女性の子供の数とする。

サンプリングモデルは以下の通り

$$
Y_{1,1}, \dots,Y_{n_{1},1}\mid\theta_{1} \sim \text{i.i.d.} \,\,Poisson(\theta_{1}),
$$

$$
Y_{1,2}, \dots,Y_{n_{2},2}\mid\theta_{2} \sim \text{i.i.d.} \,\,Poisson(\theta_{2}),
$$

```{r GSS, echo=FALSE}
# 大卒未満の女性の数と子供の合計、平均

n1 <- 111
sy1 <- 217
my1 <- 217/111

# 大卒以上の女性の数と子供の合計、平均

n2 <- 44
sy2 <- 66
my2 <- 66/44

# 事前分布のパラメータ

a <- 2
b <- 1

# 事前分布は、gamma(a = 2, b = 1) なので、事後分布はgamma(a + \sum_y, b + n)となる
# gammaは共役事前分布

# 事後平均E(\theta_{1}\mid y1) = (a+sum_y)/(b+n)

post_mean1 <- (a+sy1)/(b+n1)
post_mean1

# 95%信用区間

CI1 <- qgamma(c(0.025, 0.975), a+sy1, b+n1)
CI1


```


### 予測分布

また、以下の予測分布の比較から、傾向として$\theta_{1} > \theta_{2}$となっていることが伺える。


```{r predictive_dist}
# 予測分布のプロット
# それぞれの予測分布と共通の事前分布から乱数生成してプロットしてみる

N <- 100000

t1 <- tibble(theta = rgamma(N, a+sy1, b+n1),
             label = "theta1")
t2 <- tibble(theta = rgamma(N, a+sy2, b+n2),
             label = "theta2")
p <- tibble(theta = rgamma(N, a, b),
            label = "prior")

df <- bind_rows(t1, t2, p)


df %>% 
  ggplot(aes(x = theta, color = as.factor(label))) + 
  geom_density(aes(fill = as.factor(label), alpha = 0.5)) +  
  scale_fill_brewer(palette= "PuRd")+
  scale_color_brewer(palette = "PuRd")+
  theme_classic()



```










